# Build ASP.NET Core project using Azure Pipelines
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core?view=vsts

pool:
#  vmImage: 'Ubuntu 16.04'
  vmImage: 'vs2017-win2016'
  
variables:
  buildConfiguration: 'Release'
  Major: '0'
  Minor: '9'
  Patch: '0'


steps:
- script: |
    dotnet restore bleak.InfiniteData/bleak.InfiniteData.csproj
    dotnet restore bleak.InfiniteData.Tests/bleak.InfiniteData.Tests.csproj
  displayName: Restore
  name: Restore

- script: |
    dotnet build bleak.InfiniteData/bleak.InfiniteData.csproj --configuration $(buildConfiguration)
    dotnet build bleak.InfiniteData.Tests/bleak.InfiniteData.Tests.csproj --configuration $(buildConfiguration)
  displayName: Build
  name: Build

- script: |
    dotnet test bleak.InfiniteData.Tests --configuration $(buildConfiguration) --logger trx
  displayName: Run Tests
  name: Run_Tests

- script: |
    dotnet pack bleak.InfiniteData/bleak.InfiniteData.csproj -c $(buildConfiguration) /p:PackageVersion=$(major).$(minor).$(patch) --output $(Build.ArtifactStagingDirectory) --no-build --no-restore
  displayName: Pack
  name: Pack

- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/*.trx'

- task: PublishBuildArtifacts@1

- task: NuGetCommand@2
  inputs:
    command: push
    nuGetFeedType: external
    publishFeedCredentials: 'NuGetConnection'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg'
